/**
 * Master vocabulary of tech/skill terms recognized when scanning a lead's
 * title+body for resume-fit scoring. Deliberately excludes bare tokens that
 * are common English words or ambiguous substrings (e.g. "go", "auth") to
 * avoid false-positive matches against unrelated text.
 */
export const SKILL_VOCABULARY: readonly string[] = [
  // Frontend
  'next.js',
  'nextjs',
  'react',
  'vue',
  'vue.js',
  'angular',
  'svelte',
  'jquery',
  'typescript',
  'javascript',
  'html',
  'css',
  'tailwind',
  'tailwind css',
  'three.js',
  'threejs',
  'sass',
  'redux',
  // Backend
  'node.js',
  'nodejs',
  'node',
  'express',
  'express.js',
  'python',
  'django',
  'flask',
  'java',
  'spring',
  'spring boot',
  'php',
  'laravel',
  'ruby',
  'ruby on rails',
  'rails',
  'c#',
  '.net',
  'golang',
  'rust',
  'kotlin',
  'scala',
  'elixir',
  // APIs
  'rest api',
  'rest apis',
  'graphql',
  'grpc',
  'websocket',
  'websockets',
  // Databases
  'sql',
  'postgresql',
  'postgres',
  'mysql',
  'mongodb',
  'mongoose',
  'redis',
  'elasticsearch',
  'dynamodb',
  'firebase',
  'supabase',
  // E-commerce / CMS
  'shopify',
  'shopify headless',
  'storefront api',
  'woocommerce',
  'magento',
  'bigcommerce',
  'wordpress',
  'sanity',
  'sanity cms',
  'contentful',
  'checkout',
  // Infra / DevOps
  'aws',
  'azure',
  'gcp',
  'google cloud',
  'docker',
  'kubernetes',
  'terraform',
  'ci/cd',
  'jenkins',
  'git',
  'netlify',
  'vercel',
  'serverless',
  'microservices',
  // Mobile
  'ios',
  'android',
  'flutter',
  'react native',
  'swift',
  'objective-c',
  // Testing
  'jest',
  'cypress',
  'playwright',
  'selenium',
  // Auth / email / payments
  'jwt',
  'oauth',
  'brevo',
  'resend',
  'mailgun',
  'stripe',
  'paypal',
  // Practice
  'agile',
  'scrum',
];

/**
 * Emmanuel Amos's actual skills (extracted from his resume) — a subset of
 * SKILL_VOCABULARY. Edit this list directly to update matching; no need to
 * re-share a resume for changes.
 */
export const RESUME_SKILLS: readonly string[] = [
  'next.js',
  'nextjs',
  'react',
  'typescript',
  'html',
  'css',
  'tailwind',
  'tailwind css',
  'three.js',
  'threejs',
  'node.js',
  'nodejs',
  'node',
  'express',
  'express.js',
  'c#',
  '.net',
  'rest api',
  'rest apis',
  'graphql',
  'supabase',
  'postgresql',
  'postgres',
  'mongodb',
  'mongoose',
  'sql',
  'shopify',
  'shopify headless',
  'storefront api',
  'checkout',
  'sanity',
  'sanity cms',
  'git',
  'netlify',
  'vercel',
  'jwt',
  'brevo',
  'resend',
  'mailgun',
  'agile',
  'scrum',
];
